# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main
schedules:
 - cron: "0 8 * * *"
   displayName: Runs at 8
   branches:
    include:
     - daily-run

variables:
  DBT_CLOUD_API_TOKEN: $(API Token)

stages:
- stage: Build

  jobs:
  - job: setup
    pool:
     vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        Python37:
          python.version: '3.7'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'

    - script: |
        python -m pip install --upgrade pip
        pip install requests
      displayName: 'Install dependencies'
      
  - job: Stich
    dependsOn: setup
    condition: succeeded('setup')
    steps:
    - script: 
        python stitch_job.py


  - job: DBT
    dependsOn: stich
    condition: succeeded('stich')
    steps:
    - script: 
       python dbt.py
        
        
  - job: Power_Bi
    dependsOn: DBT
    condition: succeeded('DBT')
    steps:
    - script: 
        python power_bi.py
